### PR TITLE
Responsive layouts

### LINKED ISSUE #12: Improvement: make designs responsive for atleast 700px width
Currently, UI overflows at 1100px device width.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #12.

Does away with all the absolute positioning I could find and replaces it with glorious flexbox.

Sets up breakpoints at *580px* and *1160px* based on the existing code.

Prefers a mobile-first approach with min-width media queries.

<table>
<thead>
<tr>
<th>Area</th>
<th>Mobile (Pixel 2)</th>
<th>Tablet (iPad Pro)</th>
<th>Full (1200px)</th>
</tr>
</thead>
<tbody>
<tr>
<th>Home</th>
<td>Home screenshot at mobile resolution</td>
<td>Home screenshot at tablet resolution</td>
<td>Home screenshot at full resolution</td>
</tr>

<tr>
<th>Create Project</th>
<td>Create Project screenshot at mobile resolution</td>
<td>Create Project screenshot at tablet resolution</td>
<td>Create Project screenshot at full resolution</td>
</tr>

<tr>
<th>Starter Pack</th>
<td>Starter Pack screenshot at mobile resolution</td>
<td>Starter Pack screenshot at tablet resolution</td>
<td>Starter Pack screenshot at full resolution</td>
</tr>

</tbody>
</table>

### CODE REVIEW

**Review by evenstensberg — COMMENTED** [review]
This is golden, could you rebase?

**Comment by JoshuaKGoldberg** [comment]
Ping @evenstensberg - still interested in this PR? No worries if not, just trimming down my PR queue :)

**Comment by evenstensberg** [comment]
I think we need to re-envision the designs as the implementation spec has changed

**Comment by JoshuaKGoldberg** [comment]
Ok, I'll just close for now then. It was a fun little project 😄

**Pull request closed without merging**
